import type { MatImageRecord } from "../_lib/mat-image-types";
import type { FeaturedStory } from "../_lib/featured-story";

/**
 * Generated by scripts/write-data-ts.ts — do not hand-edit photo records
 * here. Update SLOT_MAP / per-couple photo maps in that script and re-run
 * `npx tsx scripts/write-data-ts.ts`. Story prose IS allowed to be edited
 * here directly when minor copy tweaks are needed.
 */
export const MAT_IMAGES: Record<string, MatImageRecord> = {
  hero: {
    publicId: "/images/weddings/073-dsc00466.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAMEBf/EACIQAAIBAwMFAQAAAAAAAAAAAAECAwAEESExUQUGIiNBkf/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAaEQACAwEBAAAAAAAAAAAAAAABAgADEhFB/9oADAMBAAIRAxEAPwDO6ReQqvsXJONODzS+4poneMR4Pj+VLa28caiSR2CE/BuKLqGJ8mNiQWyCRjGm1GFYD6i2fVfPZ//Z",
    width: 2400,
    height: 1640,
    source: "cloudinary",
  },
  heroAlt: {
    publicId: "/images/weddings/045-aks07419.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABAX/xAAhEAACAQQCAgMAAAAAAAAAAAABAgMABBEhBRIiQTGR0f/EABUBAQEAAAAAAAAAAAAAAAAAAAED/8QAFhEBAQEAAAAAAAAAAAAAAAAAAAER/9oADAMBAAIRAxEAPwAqkvPmLaAb1oUpSbeUkOFY6wh0f2gLyb3dwVZVHllfSrn0aocjEt3LOYukMkTqvZn0dZ+Pqp5YX//Z",
    width: 2400,
    height: 1600,
    source: "cloudinary",
  },
  cinemaQuote: {
    publicId: "/images/weddings/082-dsc05358.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAwQFBv/EACAQAAIBAwQDAAAAAAAAAAAAAAEDAgAEERITFCExYbH/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFxEBAAMAAAAAAAAAAAAAAAAAAAERIf/aAAwDAQACEQMRAD8A1rMxVIjzihWJ1Kl6nL7UpD7sxjzbkL3BgLwMk03yJIt2LSQXEExEuu6QXj//2Q==",
    width: 2400,
    height: 1600,
    source: "cloudinary",
  },
  couple1: {
    publicId: "/images/weddings/091-dsc09939.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAgMFBv/EACMQAAIBBAEDBQAAAAAAAAAAAAECAwAEERIiBQZxITFRgZH/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AM8J1OGEMGM4I0FAQ4ty5iQqWPLUeh+PFWrfte9XO8ahTjl74+qX1RQ1ulukciRoSF2jIPn9qg//2Q==",
    width: 1600,
    height: 2400,
    source: "cloudinary",
  },
  couple2: {
    publicId: "/images/weddings/084-dsc07273.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwUG/8QAIRAAAgICAQQDAAAAAAAAAAAAAQMCEQAEIQUSEzEiUWH/xAAVAQEBAAAAAAAAAAAAAAAAAAABA//EABYRAAMAAAAAAAAAAAAAAAAAAAARIf/aAAwDAQACEQMRAD8Aza4AzoyiBL1ZrEdry1/iwUbvFSiTdpEPGbuyZDiryz1JOu5UopHc1ZofZj74/co6Ch//2Q==",
    width: 1591,
    height: 2400,
    source: "cloudinary",
  },
  couple3: {
    publicId: "/images/weddings/029-aks05757ananta-10.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAMF/8QAIxAAAQMDAgcAAAAAAAAAAAAAAQIDIQAEERITFCIjMUFhsf/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAYEQACAwAAAAAAAAAAAAAAAAAAEQEhMf/aAAwDAQACEQMRAD8A2rgoetwylQ6kZB7ULhW2lB3S4FpBbDmfBzIFKbbWkKxpExV7pO5bKQOVcSJ++qO2NKEf/9k=",
    width: 2400,
    height: 1600,
    source: "cloudinary",
  },
  bride1: {
    publicId: "/images/weddings/079-dsc02192-copy.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACAQAAIBBAIDAQAAAAAAAAAAAAECAwAEERIFIRQiUWH/xAAUAQEAAAAAAAAAAAAAAAAAAAAD/8QAGREAAgMBAAAAAAAAAAAAAAAAAAECESIx/9oADAMBAAIRAxEAPwBDk0Xx8jRXIK5YUQ8UdzYPCwKEE+2AcClOVvAqJCGA3PeOyB+UcHjBWNX02JUsx+Ub6NFZs//Z",
    width: 1600,
    height: 2400,
    source: "cloudinary",
  },
  bride2: {
    publicId: "/images/weddings/067-aks09758-enhanced-nr-copy.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAMG/8QAHxAAAgICAgMBAAAAAAAAAAAAAQIDEQAEEiETMUEy/8QAFQEBAQAAAAAAAAAAAAAAAAAAAwT/xAAYEQACAwAAAAAAAAAAAAAAAAAAERIhIv/aAAwDAQACEQMRAD8AzjQzbHNoyOuyC1E5TY0ZdNUkZricDiSaN/esMJQGsMwYeiPmK2tvz66ryY0R+jdYdlMtM//Z",
    width: 1531,
    height: 2400,
    source: "cloudinary",
  },
  bride3: {
    publicId: "/images/weddings/069-aks09876-copy.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQID/8QAHhAAAgEEAwEAAAAAAAAAAAAAAQIDAAQREhMxQdH/xAAUAQEAAAAAAAAAAAAAAAAAAAAD/8QAFhEAAwAAAAAAAAAAAAAAAAAAAAER/9oADAMBAAIRAxEAPwCpH4zGqKMN2a2eEyW4mVBx47o23uty7srMmpAx6B9pcXBawfXAR1BAJyRQpUeH/9k=",
    width: 1600,
    height: 2400,
    source: "cloudinary",
  },
  portrait1: {
    publicId: "/images/weddings/092-ysp02242-copy.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAQQG/8QAIRAAAgICAgEFAAAAAAAAAAAAAQIDEQAEEjEhI1FhgcH/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAf/EABgRAQADAQAAAAAAAAAAAAAAAAEAAlED/9oADAMBAAIRAxEAPwDOQ6vpoSnIuV810Dd/mWLrQIxKSIoMZHNSPfurwim14Yg6yRmRUqiCQ3wcJtjUWEGBFR2NNxJ6+8PN2UsZP//Z",
    width: 1587,
    height: 2400,
    source: "cloudinary",
  },
  portrait2: {
    publicId: "/images/weddings/043-aks07326-copy-2.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABAX/xAAfEAABBAICAwAAAAAAAAAAAAABAgMEEQAhEjETQlH/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AjMshSVbrXfzHNQwY4skmzdijgIKpJUFNNqdF7HGwRjZDkt6d5AhTLSCe/bA//9k=",
    width: 1535,
    height: 2400,
    source: "cloudinary",
  },
  portrait3: {
    publicId: "/images/weddings/044-aks07351-edit-copy.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABAb/xAAhEAACAQMDBQAAAAAAAAAAAAABAgADERIEImEhMVHB8f/EABQBAQAAAAAAAAAAAAAAAAAAAAD/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCTVVBGfaLGjdCmaEI3Qmx2nweYJW3An5FVNW9QPd2s5yI59wP/2Q==",
    width: 1560,
    height: 2400,
    source: "cloudinary",
  },
  portrait4: {
    publicId: "/images/weddings/087-dsc07525.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAED/8QAIBAAAgEEAgMBAAAAAAAAAAAAAQMCAAUREgQhIiNBMf/EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAFhEBAQEAAAAAAAAAAAAAAAAAAQAR/9oADAMBAAIRAxEAPwDFNkt5hhpZIjI8Rjv7Q7nYkISx3EdJkFgkgipwbvrHTXEpQ1JJzk016nG3ycXK9+QYfkiPndA2oo3/2Q==",
    width: 1600,
    height: 2400,
    source: "cloudinary",
  },
  haldi: {
    publicId: "/images/weddings/001-aks00615.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwUG/8QAIBAAAgEDBAMAAAAAAAAAAAAAAQIRAAMTBAUhMTNBYf/EABUBAQEAAAAAAAAAAAAAAAAAAAIE/8QAGREAAwADAAAAAAAAAAAAAAAAAAECAyFB/9oADAMBAAIRAxEAPwDRDXwgZlSPj0T7nbZZwkr7Ibqp1iyuFlYBS8ggHqKHFeCHxjiDyRNBVT4VThlraP/Z",
    width: 1600,
    height: 2400,
    source: "cloudinary",
  },
  mehendi: {
    publicId: "/images/weddings/003-aks00880.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAAD/8QAIhAAAgEDAwUBAAAAAAAAAAAAAQIDAAQREhMhIjEyQYGh/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAT/xAAYEQEBAQEBAAAAAAAAAAAAAAABAgAhMf/aAAwDAQACEQMRAD8AJczpK6IR1c/PdSxyGOdHZTC0eQGHj2/aJdXG0i5iIZcAMxzqFZXF+raTECh29LYHBNFX3VXRUnd//9k=",
    width: 2400,
    height: 1404,
    source: "cloudinary",
  },
  sangeet: {
    publicId: "/images/weddings/016-aks04401ananta-10.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABgID/8QAIBAAAgIBAwUAAAAAAAAAAAAAAQIDEQAEBhITQVGB4f/EABUBAQEAAAAAAAAAAAAAAAAAAAME/8QAGREBAAIDAAAAAAAAAAAAAAAAAgABAzFB/9oADAMBAAIRAxEAPwA1EjyMLJN0ayyvFWUAniL+esRJtyeLR9eKQSyqAAgFX5zOLQSxqqzQsjlmUlu4OVZLa1DKPJ//2Q==",
    width: 2400,
    height: 1525,
    source: "cloudinary",
  },
  pheras: {
    publicId: "/images/weddings/011-aks02216.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAgMEBv/EACEQAAIBAwMFAAAAAAAAAAAAAAECAwAEERIhMQUTMkFh/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABcRAQEBAQAAAAAAAAAAAAAAAAEAAhH/2gAMAwEAAhEDEQA/AMxEQO0PpzQSKUnGrIPsYquC2Mc0b3Awnljk03rZVrwlNCqoA43O1ASbjQdS/9k=",
    width: 2400,
    height: 1600,
    source: "cloudinary",
  },
  vidaai: {
    publicId: "/images/weddings/038-aks06577-copy.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAwX/xAAfEAACAgEFAQEAAAAAAAAAAAABAgMRBAAFEiFREzH/xAAUAQEAAAAAAAAAAAAAAAAAAAAD/8QAFxEBAQEBAAAAAAAAAAAAAAAAAQAxQf/aAAwDAQACEQMRAD8AqxzcVDKCQa68vR4u4vMpEiiKyRdkd6nrkhNxTAv6EXLzZj+1oJsl9vES5jBjyLKasML6F+jRCuTodv/Z",
    width: 2400,
    height: 1584,
    source: "cloudinary",
  },
  reel1: {
    publicId: "/images/weddings/064-aks09456-edit-copy.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQAC/8QAHxAAAgIBBAMAAAAAAAAAAAAAAQIAEQQDEiExBSJB/8QAFAEBAAAAAAAAAAAAAAAAAAAAAP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AGtoWzXEmRXSxREKzM4LhegLMwFUee5jE8guzT0ySAR97gf/2Q==",
    width: 1552,
    height: 2400,
    source: "cloudinary",
  },
  reel2: {
    publicId: "/images/weddings/004-aks00890.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwQF/8QAHxAAAgEEAgMAAAAAAAAAAAAAAQIDAAQRMRIhE3HB/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgX/xAAaEQEAAQUAAAAAAAAAAAAAAAABAAIDERIh/9oADAMBAAIRAxEAPwCW2tpZF6UgE7IwKe1jVJ+MgLB9OrAg/ae+MyBkcjx5AzjXusx5HeRSoZjjA63R3apURuOF5P/Z",
    width: 1600,
    height: 2400,
    source: "cloudinary",
  },
  reel3: {
    publicId: "/images/weddings/075-dsc00540-edit-copy.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAwX/xAAiEAABAwIGAwAAAAAAAAAAAAABAgMRACEEEjFBgdFhcaH/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAFREBAQAAAAAAAAAAAAAAAAAAAQD/2gAMAwEAAhEDEQA/AKuGKMgU0tIMDxtTEhyErWjObQTc67cfKmtEONAAxpccdU7YQl5LovCgZn33QCS3/9k=",
    width: 2400,
    height: 1497,
    source: "cloudinary",
  },
  reel4: {
    publicId: "/images/weddings/089-dsc09759.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAQX/xAAjEAABAwQCAQUAAAAAAAAAAAABAgMEAAURIRIxBhNBYZHB/8QAFAEBAAAAAAAAAAAAAAAAAAAAAf/EABYRAQEBAAAAAAAAAAAAAAAAAAABEf/aAAwDAQACEQMRAD8AhvWtyPFZU8nipwqOAfbVMO2vvTGA22VBJBV8DZ/DVG43qHPUypS+AHaeJOM77pg+QMR5LqtKT6ZKScg5BOB9GiXC/9k=",
    width: 2400,
    height: 1459,
    source: "cloudinary",
  },
  reel5: {
    publicId: "/images/weddings/047-aks07627.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAgME/8QAIRAAAgICAgEFAAAAAAAAAAAAAQIDEQQhADEFEhQiI1H/xAAVAQEBAAAAAAAAAAAAAAAAAAACA//EABcRAAMBAAAAAAAAAAAAAAAAAAABETH/2gAMAwEAAhEDEQA/ALYXjsT3PrEIdd0r9E1+cWZ47Fd1c46xfGiqaF2eIzibKCotSRAEUOgeaJmMmU4J+ob2Kqt98FKRaf/Z",
    width: 2400,
    height: 1600,
    source: "cloudinary",
  },
  reel6: {
    publicId: "/images/weddings/022-aks05467ananta-10.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAwT/xAAgEAACAQMEAwAAAAAAAAAAAAABAgMABBEFEkFxITHw/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQL/xAAYEQEAAwEAAAAAAAAAAAAAAAABAAIRIf/aAAwDAQACEQMRAD8ASLUQYrdGBIb2Rx8ao1dxfOtvHlljGcjk1G0UNpOXQGRVAZQT4HPdAIA1y6zyNGzDeqg5A7NQ20iUR7P/2Q==",
    width: 2400,
    height: 1600,
    source: "cloudinary",
  },
  atmos1: {
    publicId: "/images/weddings/074-dsc00516-edit-copy.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAMF/8QAIxAAAgEEAQMFAAAAAAAAAAAAAQIDAAQRIQUSMVETImFxwf/EABQBAQAAAAAAAAAAAAAAAAAAAAD/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDVlvBAXj2zro5Ot1S2vwZhB7lJICnGQfvx2NE5KMLJHcBeoEdLD9pnHxAJ67Lhn7D480H/2Q==",
    width: 2400,
    height: 1324,
    source: "cloudinary",
  },
  atmos2: {
    publicId: "/images/weddings/080-dsc02517-copy.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwAF/8QAIRAAAgEEAgIDAAAAAAAAAAAAAQIDAAQRIQUSE0FRYeH/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AyeBsPLG02m+vil56wVLYSlAjq2Mj3SWNiYrRUPkYCXs2Nbx+1cha94JokEihpFYAg4XWKD//2Q==",
    width: 2400,
    height: 1595,
    source: "cloudinary",
  },
  atmos3: {
    publicId: "/images/weddings/036-aks06098ananta-10.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAID/8QAIBAAAgICAgIDAAAAAAAAAAAAAQIDEQQhADEFEhMicf/EABUBAQEAAAAAAAAAAAAAAAAAAAME/8QAFxEAAwEAAAAAAAAAAAAAAAAAAAEhEv/aAAwDAQACEQMRAD8AqXJGVirjslCBQWK610PzhFhjaH5x0DV11vjn8dKolkjkLe6BWUauuuYDClPjIYSvowP3UmtXvfDw26UakP/Z",
    width: 2400,
    height: 1630,
    source: "cloudinary",
  },
  detail1: {
    publicId: "/images/weddings/040-aks07007.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAgAD/8QAIhABAAIABgEFAAAAAAAAAAAAAQIDAAQREiExIgUTMqGx/8QAFAEBAAAAAAAAAAAAAAAAAAAABP/EABgRAAMBAQAAAAAAAAAAAAAAAAABAhEh/9oADAMBAAIRAxEAPwAVXNOsogkvF4465xZGdVfp02YgKGp8gVMbVJujUQjGJ5I8/eDnrKYb62D7evO06Xt/MGmnjGuVw//Z",
    width: 2400,
    height: 1608,
    source: "cloudinary",
  },
  detail2: {
    publicId: "/images/weddings/034-aks05996-copy.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQQG/8QAJRAAAgEEAQEJAAAAAAAAAAAAAQIDAAQREkEFBhMhMVFxkaHw/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABcRAAMBAAAAAAAAAAAAAAAAAAABERL/2gAMAwEAAhEDEQA/AFZOqWMNzLDMzs8a7EKufv8AedVsIpbdJowy7cHis3H3h7RXbaquVVth6eGPmnI5Q0AZZCcEgrx70MsdR//Z",
    width: 1585,
    height: 2400,
    source: "cloudinary",
  },
  detail3: {
    publicId: "/images/weddings/005-aks01190.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQMG/8QAHxAAAgEEAwEBAAAAAAAAAAAAAQIDAAQRIQUSQVFS/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAH/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDP8dZCdwzMMDeCM6+0+vZVMTzERXCdAC4IIIxseUJazJHpWI1iqHkliyZULD8j2oP/2Q==",
    width: 1600,
    height: 2400,
    source: "cloudinary",
  },
  detail4: {
    publicId: "/images/weddings/041-aks07081.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAgMEBf/EACMQAQACAQMCBwAAAAAAAAAAAAECAxEABBIiMQUhI0FRkfD/xAAUAQEAAAAAAAAAAAAAAAAAAAAB/8QAGBEBAAMBAAAAAAAAAAAAAAAAAQARITH/2gAMAwEAAhEDEQA/ANGvezKbLLalIAsvZ8s51NDxG/cRYxjAwHJMgOf2NFROLtupUYGculh6l8hOriHz27fek7UWgyf/2Q==",
    width: 2400,
    height: 1784,
    source: "cloudinary",
  },
  detail5: {
    publicId: "/images/weddings/021-aks05083ananta-10.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABAX/xAAiEAACAAYABwAAAAAAAAAAAAABAgADBBESIRMVIjFhcYH/xAAVAQEBAAAAAAAAAAAAAAAAAAADBP/EABkRAAIDAQAAAAAAAAAAAAAAAAABAgMRgf/aAAwDAQACEQMRAD8ARKpUCqEQ47ubaiVIkcKrqcVuCBj7y3FLmyosuSy5Ekjp0o15hSSkNJOdQWZbfL94CKwsnZvGf//Z",
    width: 2400,
    height: 2158,
    source: "cloudinary",
  },
  detail6: {
    publicId: "/images/weddings/028-aks05610ananta-10.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwIF/8QAHhAAAgEEAwEAAAAAAAAAAAAAAQIhAAMEERIiMaH/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAFxEBAQEBAAAAAAAAAAAAAAAAEQASIf/aAAwDAQACEQMRAD8A0bNhuo2BPg+1d1VRSdjyiw7p4kssgxS5wbkiooIVJnRpJHPG/9k=",
    width: 2400,
    height: 1600,
    source: "cloudinary",
  },
  detail7: {
    publicId: "/images/weddings/057-aks08640-edit-copy-1.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABQb/xAAiEAACAgEDBAMAAAAAAAAAAAABAgMRAAQFEhMUQWEiUdH/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AG7bTMkcfZhZXJphISK9/WGvp6rgSxLFa9jLGDalh26SBZ4jKaCuPA84bHsGpjkd+rpjY4gN8qH7gf//Z",
    width: 1611,
    height: 2400,
    source: "cloudinary",
  },
  detail8: {
    publicId: "/images/weddings/020-aks05037ananta-10.jpg",
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQQG/8QAHxAAAgICAgMBAAAAAAAAAAAAAQIDEQAEEiEFFTFx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQT/xAAXEQEBAQEAAAAAAAAAAAAAAAACAAEx/9oADAMBAAIRAxEAPwDPJ46cMgkikXk1Dq7xD1AQuskbcRVGwfv5jC7SRgA8QK6vJt/ZVdSQo55H532MrJgrO7f/2Q==",
    width: 2400,
    height: 1600,
    source: "cloudinary",
  },
};

export type Couple = {
  bride: string;
  groom: string;
  place: string;
  img: MatImageRecord;
  slug?: string;
  story?: FeaturedStory;
};

const ANVESHA_OMKAR_STORY: FeaturedStory = {
  coverIntro: "ANVESHA AND OMKAR'S JOURNEY REFLECTS A LOVE THAT GREW WITH TIME — FROM FRIENDSHIP TO SOMETHING DEEPLY CERTAIN, EFFORTLESS IN ITS PRESENCE AND STRONG IN ITS FOUNDATION. THEIR BOND CARRIES WARMTH, UNDERSTANDING, AND A QUIET SENSE OF BELONGING, MAKING THEIR STORY FEEL BOTH BEAUTIFULLY PERSONAL AND TIMELESS.",
  date: "Fairmont Jaipur — Three Days",
  detailLine: "Two celebrations · One love · 2,140 frames",
  photos: {
    hero: {
      publicId: "/images/weddings/030-aks05781-recovered-copy.jpg",
      blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQIE/8QAIRAAAgEDAwUAAAAAAAAAAAAAAQIDABEhBBNRBRIxQfD/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAFhEAAwAAAAAAAAAAAAAAAAAAACEx/9oADAMBAAIRAxEAPwB3V7ZRy17qvoZqZE244SrFxIfIxYc0OvUnkaWQnCE45rS+vWRNMysQOzIt9ahWOI//2Q==",
      width: 1674,
      height: 2400,
      source: "cloudinary",
    },
    storyImage1: {
      publicId: "/images/weddings/023-aks05540ananta-10.jpg",
      blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABgED/8QAHxAAAgEEAgMAAAAAAAAAAAAAAQIRAAMEMRJBccHR/8QAFAEBAAAAAAAAAAAAAAAAAAAAAP/EABURAQEAAAAAAAAAAAAAAAAAAAAR/9oADAMBAAIRAxEAPwBHj5Qe3N4qj9idVuWC7YAeaO2s8ZGTethDxLcZ7n3VyXKM8GAsd7+Uo//Z",
      width: 2400,
      height: 1603,
      source: "cloudinary",
    },
    storyImage2: {
      publicId: "/images/weddings/036-aks06098ananta-10.jpg",
      blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAID/8QAIBAAAgICAgIDAAAAAAAAAAAAAQIDEQQhADEFEhMicf/EABUBAQEAAAAAAAAAAAAAAAAAAAME/8QAFxEAAwEAAAAAAAAAAAAAAAAAAAEhEv/aAAwDAQACEQMRAD8AqXJGVirjslCBQWK610PzhFhjaH5x0DV11vjn8dKolkjkLe6BWUauuuYDClPjIYSvowP3UmtXvfDw26UakP/Z",
      width: 2400,
      height: 1630,
      source: "cloudinary",
    },
    bride: {
      publicId: "/images/weddings/033-aks05973-recovered-copy.jpg",
      blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQED/8QAIRAAAgEEAgIDAAAAAAAAAAAAAQMCAAQREgUhIjETYYH/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAFxEBAQEBAAAAAAAAAAAAAAAAAQARMf/aAAwDAQACEQMRAD8AxRwKkS3ZEs0iZSJHj+imrXkQt603FqpKZnVclnqP0akroaGQ7AByB7Io9sENb8bsnHlE59UFxkA9v//Z",
      width: 1549,
      height: 2400,
      source: "cloudinary",
    },
    groom: {
      publicId: "/images/weddings/021-aks05083ananta-10.jpg",
      blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABAX/xAAiEAACAAYABwAAAAAAAAAAAAABAgADBBESIRMVIjFhcYH/xAAVAQEBAAAAAAAAAAAAAAAAAAADBP/EABkRAAIDAQAAAAAAAAAAAAAAAAABAgMRgf/aAAwDAQACEQMRAD8ARKpUCqEQ47ubaiVIkcKrqcVuCBj7y3FLmyosuSy5Ekjp0o15hSSkNJOdQWZbfL94CKwsnZvGf//Z",
      width: 2400,
      height: 2158,
      source: "cloudinary",
    },
    haldi: {
      publicId: "/images/weddings/022-aks05467ananta-10.jpg",
      blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAwT/xAAgEAACAQMEAwAAAAAAAAAAAAABAgMABBEFEkFxITHw/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQL/xAAYEQEAAwEAAAAAAAAAAAAAAAABAAIRIf/aAAwDAQACEQMRAD8ASLUQYrdGBIb2Rx8ao1dxfOtvHlljGcjk1G0UNpOXQGRVAZQT4HPdAIA1y6zyNGzDeqg5A7NQ20iUR7P/2Q==",
      width: 2400,
      height: 1600,
      source: "cloudinary",
    },
    mehendi: {
      publicId: "/images/weddings/034-aks05996-copy.jpg",
      blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQQG/8QAJRAAAgEEAQEJAAAAAAAAAAAAAQIDAAQREkEFBhMhMVFxkaHw/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABcRAAMBAAAAAAAAAAAAAAAAAAABERL/2gAMAwEAAhEDEQA/AFZOqWMNzLDMzs8a7EKufv8AedVsIpbdJowy7cHis3H3h7RXbaquVVth6eGPmnI5Q0AZZCcEgrx70MsdR//Z",
      width: 1585,
      height: 2400,
      source: "cloudinary",
    },
    sangeet: {
      publicId: "/images/weddings/018-aks04776ananta-10.jpg",
      blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAgX/xAAfEAACAQMFAQAAAAAAAAAAAAABEQIAAxIFISJRYQT/xAAVAQEBAAAAAAAAAAAAAAAAAAACA//EABcRAQEBAQAAAAAAAAAAAAAAAAERABL/2gAMAwEAAhEDEQA/AKFu6jMz2fI++UfpuRMIhsTfLpUY6cRiQrqCxJxC97NCenzkC4i0RsjyEgqmWxMqc7//2Q==",
      width: 2400,
      height: 1558,
      source: "cloudinary",
    },
    pheras: {
      publicId: "/images/weddings/031-aks05784ananta-10.jpg",
      blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABAP/xAAiEAACAQMEAgMAAAAAAAAAAAABAhIAAxEEEyFBBSIxUeH/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/EABcRAAMBAAAAAAAAAAAAAAAAAAABESH/2gAMAwEAAhEDEQA/AG35aq0iy2xPBNv9qJ8fK2j272o9BiKmOPo80hEgqruBY/OOxSH1RU8JLIwT2KJS2osP/9k=",
      width: 1600,
      height: 2400,
      source: "cloudinary",
    },
    vidaai: {
      publicId: "/images/weddings/035-aks06044ananta-10.jpg",
      blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQMEBf/EACEQAAICAQMFAQAAAAAAAAAAAAEDAhEABDFREiEiMkHR/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABgRAAMBAQAAAAAAAAAAAAAAAAABIQIR/9oADAMBAAIRAxEAPwDDcvSOUySoFZjRoHc8gcfuRJUuYkJTIlVxFfcY1vuC0s7V1EVeDTsWDGh5A7ywqD0lOH//2Q==",
      width: 1600,
      height: 2400,
      source: "cloudinary",
    },
    intimateBW: {
      publicId: "/images/weddings/032-aks05861ananta-10.jpg",
      blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQME/8QAHxAAAgICAgMBAAAAAAAAAAAAARECAwAEEkEiMVGh/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAH/xAAWEQEBAQAAAAAAAAAAAAAAAAAAESH/2gAMAwEAAhEDEQA/AFoShY4khI+svpQiLjaCYDgk0JDonCtHWOnX5oz48pSf3r8zcYxupqIkimm0cLMr/9k=",
      width: 2400,
      height: 1682,
      source: "cloudinary",
    },
    closing: {
      publicId: "/images/weddings/026-aks05564ananta-10.jpg",
      blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAgMF/8QAHhAAAgICAgMAAAAAAAAAAAAAAQIDEQAEISMxUbH/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/EABURAQEAAAAAAAAAAAAAAAAAAAEA/9oADAMBAAIRAxEAPwCkEUojaNmk4Isk+B9w7mr1pLEZEVrJI4s3mkyg7DolAMAKxb3VpxL6NVdZMoX/2Q==",
      width: 2400,
      height: 1600,
      source: "cloudinary",
    },
  },
  sections: [
    {
      heading: "Celebration of Love",
      style: "script",
      paragraphs: [
        "Anvesha and Omkar, it started with conversations that felt easy, moments that felt familiar, and a bond that quietly grew stronger with time. What began as friendship slowly unfolded into something deeper—something steadier. Not rushed, not forced—just naturally becoming love. They stood by each other through phases, changes, and everything in between, building a connection rooted in understanding and trust. It wasn't just about falling in love—it was about choosing each other, every single day.",
        "Before the traditions, before the rituals, they chose to celebrate their love in a way that felt true to them—an intimate American-style wedding, simple, personal, and filled with meaning. And then, surrounded by the warmth of family and culture, they stepped into their Indian wedding—rich in rituals, emotions, and legacy. Two celebrations. Two worlds. One love. For us, capturing Anvesha & Omkar wasn't about documenting events—it was about witnessing a journey that evolved beautifully over time. From friendship to forever, their story is a reminder that the strongest love is the one that grows with you. And in their story, love wasn't just found. It was built.",
      ],
    },
    {
      heading: "Stillness, in their language",
      style: "serif",
      paragraphs: [
        "Some stories don't need movement to be felt; they exist in stillness, and that's exactly how we chose to capture this couple. Instead of chasing loud moments or building heavy setups, we slowed everything down and focused on what truly matters—their presence with each other. Our approach was simple: clean frames, no distractions, no unnecessary elements—just them.",
        "We treated every shot like a still photograph, where composition, light, and silence carry the emotion. There were no exaggerated poses or performative expressions; instead, we observed the in-between moments—the way they naturally stood close, how their eyes met and lingered, the quiet comfort in their body language. Each frame was intentional, minimal, and deeply aesthetic, allowing their connection to breathe without interruption.",
        "The idea was not to create a story through action, but to reveal it through calm, controlled stillness. In a world where everything moves fast, we chose to pause time for them, to document their love in its most undisturbed form. What we created wasn't just a pre-wedding shoot, but a collection of frames that feel timeless—images you don't just see, but sit with, where nothing demands attention, yet everything is felt quietly and completely.",
      ],
    },
    {
      heading: "At Fairmont Jaipur",
      style: "serif",
      paragraphs: [
        "At Fairmont Jaipur, Anvesha & Omkar's wedding came alive through a perfect balance of elegance and emotion. The space carried a quiet grandeur — allowing every moment to feel both intimate and larger than life. Anvesha & Omkar carry a presence that feels natural and unforced. There's ease in the way they exist together — playful, grounded, and deeply connected. Every moment with them felt real, not performed — just two people being completely themselves, and that's what made everything truly stand out.",
      ],
    },
  ],
  pullQuote: {"word":"THEM","color":"#C41E1E"},
  vendors: [],
};

const HARSH_POOJA_STORY: FeaturedStory = {
  coverIntro: "HARSH AND POOJA'S JOURNEY REFLECTS A BOND THAT UNFOLDED WITH TIME — FROM A SIMPLE BEGINNING TO SOMETHING DEEPLY CERTAIN, ROOTED IN UNDERSTANDING AND SHAPED BY PATIENCE. THEIR CONNECTION CARRIES A QUIET STRENGTH, WHERE COMFORT MEETS COMMITMENT, MAKING THEIR STORY FEEL BOTH SINCERE AND TIMELESS.",
  date: "ITC Mughal, Agra — Three Days",
  detailLine: "Near the Taj Mahal · Sandstone & sindoor · 1,920 frames",
  photos: {
    hero: {
      publicId: "/images/weddings/065-aks09538-copy.jpg",
      blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQMFBv/EAB8QAAEEAgIDAAAAAAAAAAAAAAEAAgMRBBIhMRNRkf/EABQBAQAAAAAAAAAAAAAAAAAAAAH/xAAYEQADAQEAAAAAAAAAAAAAAAAAARICEf/aAAwDAQACEQMRAD8A1r5Q060SfSW9okHSly5UszNS6nCjwOCjDl5B28zXUaIf1fxFcF4pH//Z",
      width: 1600,
      height: 2400,
      source: "cloudinary",
    },
    storyImage1: {
      publicId: "/images/weddings/060-aks08745.jpg",
      blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAEDBP/EACUQAAIABAQHAQAAAAAAAAAAAAECAAMEESEiMWEFEhMUI0FxUf/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAXEQADAQAAAAAAAAAAAAAAAAAAAQID/9oADAMBAAIRAxEAPwDBJ4c7U4OCzHuxcsALaWh9r0aVWcMmZgcwvsRtFknoktCH8aZmDG5c/v3WCpqpAVJvKVRwUOGJB++oK0G4P//Z",
      width: 2400,
      height: 1600,
      source: "cloudinary",
    },
    storyImage2: {
      publicId: "/images/weddings/072-dsc00448-edit-copy.jpg",
      blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAQX/xAAgEAACAgICAgMAAAAAAAAAAAABAgMEABEhMQUSE0FR/8QAFAEBAAAAAAAAAAAAAAAAAAAAA//EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/ALN+6KKKSskjPvSpz194+PurejZlWSNkOircHGzWWxPHIwY+gIAB/ca0AhsTSAEfJonnrQ1hkf/Z",
      width: 1600,
      height: 2400,
      source: "cloudinary",
    },
    bride: {
      publicId: "/images/weddings/052-aks07707.jpg",
      blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAgMEBf/EAB8QAAIBBAIDAAAAAAAAAAAAAAECAwAEEUESIQUxYf/EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAGBEAAwEBAAAAAAAAAAAAAAAAABESAQL/2gAMAwEAAhEDEQA/ANi4khbDIQZMaGtVIsa207N0jmNmBA1uiupWWXiCikYyPvvNK8hIGtg+VYBeBHfZNCnpSFyz/9k=",
      width: 2400,
      height: 1600,
      source: "cloudinary",
    },
    groom: {
      publicId: "/images/weddings/066-aks09691-copyjpg.jpg",
      blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAgQF/8QAIRAAAgICAgEFAAAAAAAAAAAAAQIDEQAhBBIiMWFx0fD/xAAUAQEAAAAAAAAAAAAAAAAAAAAD/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AuJR2EfjZrV4HiLM6rQYE3qh+3mWvMLEhFWN1c7cgdlPufQ/WOPkzrIHlUAdaAUgr83hFf//Z",
      width: 1598,
      height: 2400,
      source: "cloudinary",
    },
    haldi: {
      publicId: "/images/weddings/001-aks00615.jpg",
      blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwUG/8QAIBAAAgEDBAMAAAAAAAAAAAAAAQIRAAMTBAUhMTNBYf/EABUBAQEAAAAAAAAAAAAAAAAAAAIE/8QAGREAAwADAAAAAAAAAAAAAAAAAAECAyFB/9oADAMBAAIRAxEAPwDRDXwgZlSPj0T7nbZZwkr7Ibqp1iyuFlYBS8ggHqKHFeCHxjiDyRNBVT4VThlraP/Z",
      width: 1600,
      height: 2400,
      source: "cloudinary",
    },
    mehendi: {
      publicId: "/images/weddings/012-aks02249.jpg",
      blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwEF/8QAIhAAAgEDBAIDAAAAAAAAAAAAAQIDAAQSBREhMRNBcZHw/8QAFAEBAAAAAAAAAAAAAAAAAAAAA//EABkRAAMAAwAAAAAAAAAAAAAAAAACERITMf/aAAwDAQACEQMRAD8A0rSwSBBG68Y8kj7qz6fD40kt12xPfXzS3F1I4UYYxuvD9/jRSaqhaGKNC3kGx39GjzXg2ppT/9k=",
      width: 2400,
      height: 1600,
      source: "cloudinary",
    },
    sangeet: {
      publicId: "/images/weddings/051-aks07700.jpg",
      blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQME/8QAJBAAAQMCBAcAAAAAAAAAAAAAAQIDBAARBRIhMQYTMkFRYaL/xAAVAQEBAAAAAAAAAAAAAAAAAAABBP/EABoRAAICAwAAAAAAAAAAAAAAAAABAhEDEiH/2gAMAwEAAhEDEQA/AC48V9QKgyVtp0Nj39HzWKRncdIbbUjToN707HWFYBDFxfnAfRq/EC0RYzboyh03bGm4O9Lk6opeTZdP/9k=",
      width: 2400,
      height: 1600,
      source: "cloudinary",
    },
    pheras: {
      publicId: "/images/weddings/011-aks02216.jpg",
      blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAgMEBv/EACEQAAIBAwMFAAAAAAAAAAAAAAECAwAEERIhMQUTMkFh/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABcRAQEBAQAAAAAAAAAAAAAAAAEAAhH/2gAMAwEAAhEDEQA/AMxEQO0PpzQSKUnGrIPsYquC2Mc0b3Awnljk03rZVrwlNCqoA43O1ASbjQdS/9k=",
      width: 2400,
      height: 1600,
      source: "cloudinary",
    },
    vidaai: {
      publicId: "/images/weddings/062-aks08780.jpg",
      blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAwT/xAAfEAACAQQDAQEAAAAAAAAAAAABAgMABBESFCExItH/xAAUAQEAAAAAAAAAAAAAAAAAAAAD/8QAFxEBAQEBAAAAAAAAAAAAAAAAAREAAv/aAAwDAQACEQMRAD8AW0VeNDcxfbknK46oZtI3SaKQFmJJGmQCantLrhxlOtR7genOf2pZL6UogbZSNgUI6wSaM6c0JXf/2Q==",
      width: 2400,
      height: 1472,
      source: "cloudinary",
    },
    intimateBW: {
      publicId: "/images/weddings/005-aks01190.jpg",
      blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQMG/8QAHxAAAgEEAwEBAAAAAAAAAAAAAQIDAAQRIQUSQVFS/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAH/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDP8dZCdwzMMDeCM6+0+vZVMTzERXCdAC4IIIxseUJazJHpWI1iqHkliyZULD8j2oP/2Q==",
      width: 1600,
      height: 2400,
      source: "cloudinary",
    },
    closing: {
      publicId: "/images/weddings/091-dsc09939.jpg",
      blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAgMFBv/EACMQAAIBBAEDBQAAAAAAAAAAAAECAwAEERIiBQZxITFRgZH/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AM8J1OGEMGM4I0FAQ4ty5iQqWPLUeh+PFWrfte9XO8ahTjl74+qX1RQ1ulukciRoSF2jIPn9qg//2Q==",
      width: 1600,
      height: 2400,
      source: "cloudinary",
    },
  },
  sections: [
    {
      heading: "Chosen, Then Felt",
      style: "serif",
      paragraphs: [
        "Some stories begin with a meeting — and slowly turn into something meant to be. Harsh and Pooja's journey started as an arranged match, with simple conversations that gradually grew into comfort, understanding, and a connection neither of them expected so naturally. In each other, they didn't just find a partner, but a sense of familiarity that felt right.",
        "What began as two individuals getting to know one another soon unfolded into love — quiet, steady, and certain. With every passing day, their bond deepened, built on trust, laughter, and a growing sense of belonging. A story not rushed, but beautifully realised.",
        "Harsh and Pooja come from a small town, but their taste carries a quiet elegance that stands out effortlessly. With their wedding unfolding near the Taj Mahal, we knew the visuals had to reflect the same grace the location holds. Instead of overpowering the frames, we chose a restrained approach — clean compositions, soft light, and intentional framing that allowed both them and the surroundings to exist in harmony.",
        "Their connection is simple, genuine, and deeply rooted, which made it important for us to keep everything real and undisturbed. We avoided unnecessary elements, focusing only on what mattered — the way they stand together, the subtle expressions, the ease they share. Every frame was designed to feel timeless, where the beauty of the Taj enhances their story rather than taking over it. It wasn't about creating something grand, but about matching their elegance with a setting that naturally reflects it — capturing a love that feels steady, graceful, and effortlessly beautiful.",
      ],
    },
    {
      heading: "Set against the regal charm",
      style: "serif",
      paragraphs: [
        "Set against the regal charm of ITC Mughal, Agra, Harsh and Pooja's wedding unfolded with timeless elegance and quiet grandeur. With a distant glimpse of the Taj Mahal, the setting carried a rare kind of romance — where heritage, beauty, and emotion came together effortlessly, creating a celebration that felt both intimate and iconic.",
      ],
    },
    {
      heading: "The Elegant Bride",
      style: "serif",
      paragraphs: [
        "POOJA HOLDS A PRESENCE THAT DOESN'T SEEK ATTENTION, YET NATURALLY DRAWS IT. THERE'S A QUIET CONFIDENCE IN THE WAY SHE CARRIES HERSELF — COMPOSED, GROUNDED, AND BEAUTIFULLY REAL. IN EVERY MOMENT, SHE FEELS EFFORTLESS, LEAVING BEHIND A SOFTNESS THAT STAYS, LONG AFTER EVERYTHING ELSE FADES.",
      ],
    },
  ],
  pullQuote: {"word":"QUIETUDE"},
  vendors: [],
};

export const FEATURED: Couple[] = [
  {
    bride: "Anvesha",
    groom: "Omkar",
    place: "Fairmont Jaipur",
    img: ANVESHA_OMKAR_STORY.photos.hero,
    slug: "anvesha-sang-omkar",
    story: ANVESHA_OMKAR_STORY,
  },
  {
    bride: "Pooja",
    groom: "Harsh",
    place: "ITC Mughal, Agra",
    img: HARSH_POOJA_STORY.photos.hero,
    slug: "harsh-sang-pooja",
    story: HARSH_POOJA_STORY,
  },
  { bride: "Riya",   groom: "Mohit",   place: "Udaipur",         img: MAT_IMAGES.couple1, slug: "riya-sang-mohit" },
  { bride: "Saanvi", groom: "Aditya",  place: "Goa",             img: MAT_IMAGES.couple3, slug: "saanvi-sang-aditya" },
  { bride: "Ishita", groom: "Rohan",   place: "Jodhpur",         img: MAT_IMAGES.bride1,  slug: "ishita-sang-rohan" },
  { bride: "Meher",  groom: "Devansh", place: "Florence, Italy", img: MAT_IMAGES.bride3,  slug: "meher-sang-devansh" },
];

export const RITUALS: { num: string; name: string; desc: string; img: MatImageRecord }[] = [
  { num: "01", name: "Haldi",   desc: "A morning of turmeric, laughter, and family hands.", img: MAT_IMAGES.haldi },
  { num: "02", name: "Mehendi", desc: "Hours of henna while the women sing the old songs.", img: MAT_IMAGES.mehendi },
  { num: "03", name: "Sangeet", desc: "The night before. Dholki, dance, and dupatta blur.", img: MAT_IMAGES.sangeet },
  { num: "04", name: "Pheras",  desc: "Seven steps around the fire. The vow itself.",       img: MAT_IMAGES.pheras },
  { num: "05", name: "Vidaai",  desc: "The threshold. The handful of rice. The car door.",  img: MAT_IMAGES.vidaai },
];
